# Generated by Django 3.1.1 on 2020-09-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.CharField(max_length=20)),
                ('donor_name', models.CharField(max_length=100)),
                ('donor_blood_group', models.CharField(max_length=20)),
                ('donor_email', models.EmailField(max_length=254)),
                ('donor_contact', models.CharField(max_length=11)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
