# Generated by Django 3.1.1 on 2020-09-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortprojectapp', '0002_auto_20200914_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='donor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
